version: "3.0"
services:
  messagebroker:
    container_name: messagebroker
    image: "messagebroker:latest"
    hostname: "messagebroker"
    volumes:
      - rabbit1:/var/lib/rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  rabbit1:
    driver: local